In [1]:
import pandas as pd
import numpy as np

In [2]:
airlines = pd.read_csv('airlines_final.csv')
airlines.head()

,id,day,airline,destination,dest_region,dest_size,boarding_area,dept_time,wait_min,cleanliness,safety,satisfaction
0,1351,Tuesday,UNITED INTL,KANSAI,Asia,Hub,Gates 91-102,12/31/2018,115,Clean,Neutral,Very satisfied
1,373,Friday,ALASKA,SAN JOSE DEL CABO,Canada/Mexico,Small,Gates 50-59,12/31/2018,135,Clean,Very safe,Very satisfied
2,2820,Thursday,DELTA,LOS ANGELES,West US,Hub,Gates 40-48,12/31/2018,70,Average,Somewhat safe,Neutral
3,1157,Tuesday,SOUTHWEST,LOS ANGELES,West US,Hub,Gates 20-39,12/31/2018,190,Clean,Very safe,Somewhat satsified
4,2992,Wednesday,AMERICAN,MIAMI,East US,Hub,Gates 50-59,12/31/2018,559,Somewhat clean,Very safe,Somewhat satsified

In [3]:
airlines['dept_time'] = airlines['dept_time'].str.replace('/','-')
airlines.head()

,id,day,airline,destination,dest_region,dest_size,boarding_area,dept_time,wait_min,cleanliness,safety,satisfaction
0,1351,Tuesday,UNITED INTL,KANSAI,Asia,Hub,Gates 91-102,12-31-2018,115,Clean,Neutral,Very satisfied
1,373,Friday,ALASKA,SAN JOSE DEL CABO,Canada/Mexico,Small,Gates 50-59,12-31-2018,135,Clean,Very safe,Very satisfied
2,2820,Thursday,DELTA,LOS ANGELES,West US,Hub,Gates 40-48,12-31-2018,70,Average,Somewhat safe,Neutral
3,1157,Tuesday,SOUTHWEST,LOS ANGELES,West US,Hub,Gates 20-39,12-31-2018,190,Clean,Very safe,Somewhat satsified
4,2992,Wednesday,AMERICAN,MIAMI,East US,Hub,Gates 50-59,12-31-2018,559,Somewhat clean,Very safe,Somewhat satsified

In [8]:
assert airlines['dept_time'].str.contains('/ | &').any() == False

This asserts that the dept_time column values dont contain the symbols / and &.

### Considering destinations with short names only

In [10]:
dest_length = airlines['destination'].str.len()

short_len = airlines[dest_length < 10]

print(short_len['destination'])

0          KANSAI
4           MIAMI
5          NEWARK
8         TORONTO
9        PORTLAND
          ...
2469    HONG KONG
2471       AUSTIN
2473      PHOENIX
2474      ORLANDO
2476      QINGDAO
Name: destination, Length: 1476, dtype: object